### ISSUE TITLE
你好，请问怎么训练啊？

### ISSUE THREAD

**Issue by dingtao1** [gniknoil/Perfect500K-Beauty-Product-Retrieval-Challenge#1]
模型是在imganet上训练吗？还是这个比赛有个训练数据集吗？

**Comment by gniknoil** [comment]
没有训练集，只能找别的数据集上预训练的权重 xiegc ***@***.*** 签名由 网易邮箱大师 定制 在2021年04月21日 15:34，dingtao1 写道： 模型是在imganet上训练吗？还是这个比赛有个训练数据集吗？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by dingtao1** [comment]
> 没有训练集，只能找别的数据集上预训练的权重 xiegc ***@***.*** 签名由 网易邮箱大师 定制 在2021年04月21日 15:34，dingtao1 写道： 模型是在imganet上训练吗？还是这个比赛有个训练数据集吗？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

可以留个联系方式吗，想请教一些问题。我邮箱dingtao@stu.scu.edu.cn
